### ISSUE TITLE
Validation code with std environment

### ISSUE THREAD

**Issue by dm4** [substrate-developer-hub/substrate-parachain-template#10]
Following [evmc][] interface, our pallet need to load `.so` library file to create a vm. We could only execute these codes in `std` environment but looks like these codes are not generated into validation code using `parachain-collator export-genesis-wasm > para-wasm.wasm`.

Therefore, when we trying to send our pallet extrinsic, our local test relay chain could not verify new block with the following error:
```
panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/f397f24/frame/executive/src/lib.rs:398:9
```

Is there any solution or workaround for this problem? Thanks!

[evmc]: https://github.com/ethereum/evmc

**Comment by riusricardo** [comment]
@dm4 All the runtime code needs to be no_std compatible. The relay-chain will validate your parachain using the WASM blob, so if it doesn't compile to WASM it can't become a parachain.
