### ISSUE TITLE
Don't use default weights in the runtime

### ISSUE THREAD

**Issue by ggwpez** [substrate-developer-hub/substrate-parachain-template#102]
Analogous to https://github.com/paritytech/cumulus/pull/1081

Instead of relying on the default weights from `frame_support`; copy in the weights files and use them.  
This way we encourage developers to benchmark their own weights and create a more future proof structure.

**Comment by NukeManDan** [comment]
this should be implemented on Cumulus, not the devhub version of the template :pray: perhaps close this issue and open one upstream?

**Comment by ggwpez** [comment]
Gonna do it upstream instead.
