### ISSUE TITLE
Inconsistent behaviour on extracting genesis state

### ISSUE THREAD

**Issue by chrisdcosta** [substrate-developer-hub/substrate-parachain-template#118]
### Error summary

We have three conflicting genesis states that can be extracted from the same raw chain spec under the three conditions outline here. 

We conclude that we cannot rely on the `export-genesis-state` command to provide the correct genesis state in all circumstances - it provides different results when extracting or running the compiled code or the docker container.

The method that we used to generate the state is found in the file `extraction.sh` in our repo but the relevant commands are copied here. The methods we used to extract the states did not cause an issue on our testnet which you can access from Polkadotjs apps. It is happily producing blocks.

Relaychain [wss://relaychain.kapex.network](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frelaychain.totem.live#/explorer)

Parachain (needs polkadotjs apps to run locally to connect as no cert is used) 
[ws://159.89.1.153:22222](http://localhost:3000/?rpc=ws%3A%2F%2F159.89.1.153%3A22222#/explorer)

The issue was discovered because the Kapex Parachain should have been producing blocks immediately after it won a slot but is not due to this error which we interpret to be an issue with the Genesis State uploaded to Polkadot.

`2022-06-25 09:27:12 [Parachain] Could not find the header of the genesis block in the database! block_hash=0x7838c3c774e887c0a53bcba9e64f702361a1a852d5550b86b58cd73827fa1e1e`

### Environment and prerequisites

Navigate to [our parachain repo](https://github.com/totem-tech/totem-parachains) which is a fork of this repo created for our parachain.

### Code

**NOTE: Compiling at the root this will fail as it attempts to compile all pallets in the repo some of which are not ready for including in the parachain and are not yet included in our parachain node.**

Therefore to compile `totem-parachain-collator` run this specific command. 

`cargo build --release -p totem-parachain-node`

You will also need the docker image from docker hub:

`docker pull totemlive/totem-parachain-collator:latest`

### Instructions to reproduce error:

---

**State 1. Original genesis state after compilation (on macOS) extracted from json raw file.**

> This was the state that was uploaded to Polkadot as parachain 2007. 

This is also the state we observe when the extraction command is run from the compiled binary on linux 20.04 VPS. In other words these two states agree when two different machines and operating systems using the same command.

However they do not agree with the states observed when starting the nodes - see State 2 and State 3 below.

* command used to extract found in extraction.sh file in repo: 

```shell
./target/release/totem-parachain-collator export-genesis-state --chain ./res/kapex/kapex-parachain-raw.json > ./res/kapex/kapex-genesis-state-new.state
```

* command also works like this

```shell
./target/release/totem-parachain-collator export-genesis-state --chain=kapex
```

State 1 Output:

```shell
0x0000000000000000000000000000000000000000000000000000000000000000006a033ba2e46dad9c9c0a1f93fb17752e43299385aeee4875ddcef275e5a5417303170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
```

Conclusion here is that we are not able to run any version that produces this chain state at all as described below. 

---

**State 2. Run node from docker on vps referencing the kapex chain as is included in the node 'command.rs' and 'chains_spec.rs' files.**

The `command.rs` file takes the chain argument and executes the instruction to include the chainspec raw file according to the relevant entry in `chain_spec.rs`. 

This produces a different state to state 1 even though it is referencing the same raw file in the same directory as in state 1.

This new state is also reported by the collators during startup. Note that the collators use the docker image and are infrastructure setup using K8s - but this makes no difference as it is reproducible.

* basic command used to run the docker image:

```shell
docker run \
--rm \
-v="/$(pwd):/data" \
totemlive/totem-parachain-collator:latest \
totem-parachain-collator
```

```shell
"2022-06-25 09:23:45 Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000e96503849454d1f65ad1eb521b4b798ddb661d1bb289d27d5c04089dfdd5563403170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400"
```

This genesis state should be identical to the state generated from the raw chain spec file in in 1) above. It is not. 

I believe this is the primary reason why the collators do not agree with the state recorded in Polkadot.

Also tested the extraction : 

* command used to extract state using docker referencing the chain command: 

```shell
docker run \
--rm \
-v="/$(pwd):/data" \
totemlive/totem-parachain-collator:latest \
totem-parachain-collator \
export-genesis-state \
--chain=kapex
```

State 2 Output:

```shell
0x000000000000000000000000000000000000000000000000000000000000000000e96503849454d1f65ad1eb521b4b798ddb661d1bb289d27d5c04089dfdd5563403170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
````

---

**State 3. Using the raw chainspec from the repo extracting with docker, and running the node from compiled binary on the vps**

This is yet another state which does not agree with the previous two states.

* command used executing binary:

```shell
./target/release/totem-parachain-collator \
--state-cache-size=1 \
--chain=$(pwd)/res/kapex/kapex-parachain-raw.json \
--base-path $(pwd) \
--execution=wasm \
--name "kapex-VPS-node" \
--public-addr /ip4/<ipadress>/tcp/<port1> \
--port port1 \
--collator \
-- \
--chain polkadot \
--execution=wasm \
--public-addr /ip4/<ipadress>/tcp/<port2> \
--port port2
```

It is also identical to the state that is seen when not referencing the file and using the direct command

```shell
./target/release/totem-parachain-collator \
--state-cache-size=1 \
--chain=kapex \
--base-path $(pwd) \
--execution=wasm \
--name "kapex-VPS-node" \
--public-addr /ip4/<ipadress>/tcp/<port1> \
--port port1 \
--collator \
-- \
--chain polkadot \
--execution=wasm \
--public-addr /ip4/<ipadress>/tcp/<port2> \
--port port2
```

```shell
2022-06-25 12:36:43 Parachain genesis state: 0x000000000000000000000000000000000000000000000000000000000000000000ddf220b021c1a496ee908681e333c7597d4661759bbe5e261c61905a88eb482403170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400    
```

* command using docker image: 

```shell
docker run \
--rm \
-v="/$(pwd):/data" \
totemlive/totem-parachain-collator:latest \
totem-parachain-collator \
export-genesis-state \
--chain="/data/kapex-parachain-raw.json"
```

State 3 Output:

```shell
0x000000000000000000000000000000000000000000000000000000000000000000ddf220b021c1a496ee908681e333c7597d4661759bbe5e261c61905a88eb482403170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400
```

**Comment by NukeManDan** [comment]
This is unfortunately*know expected behavior*. Wasm is not expected to be deterministic, as pointed out in the docs in a few places. You _must_ buid these in a single environment and distribute them. 

@chevdor has some tooling pinned in his repos around the https://github.com/paritytech/srtool that may be if interest to help set a consistent, deterministic build and file generation. Again though, you want to make this once and distribute it. 

> If you intend to let others connect to your network, they must have the associated chain spec for your network generated once and distributed to your peers. They cannot reliably produce this themselves, and need to acquire it from a single source. This stems from the [non-deterministic issue](https://dev.to/gnunicorn/hunting-down-a-non-determinism-bug-in-our-rust-wasm-build-4fk1) in the way Wasm runtimes are compiled.

> Chain specs conventionally live in a /chain-specs folder that is published in your node's codebase for others to use.

> It is good practice to commit this raw chain spec into your source before proceeding.

**Comment by chrisdcosta** [comment]
I am already already aware of non-deterministic issue and SRtool and we have a consistent WASM build that is shared consistently, because this is a parachain that has the wasm code built into the genesis file, and furthermore the `--execution=wasm` is used.

This is not the issue raised here. 

The issue is that the extraction of the **_genesis state_** is not consistent - but not across environments - it's inconsistent _in the same environment_, when you execute equivalent commands, but get different results. The wasm is not being built in different ways it's all using the same wasm file.

@NukeManDan  I don't accept the `won't fix` label because our parachain is live but not producing blocks due to the fact that there is no clear answer.

**Comment by chrisdcosta** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/1393274/175783183-0724dcf8-665b-4239-8f0b-b1b126d2de48.png">

https://docs.substrate.io/tutorials/connect-other-chains/parachain/

**Comment by shawntabrizi** [comment]
Which genesis did you use to register your chain? End of the day, you need to generate a single genesis file, use that for the registration, and also share it with all the nodes (usually by integrating it into your binary), and have everyone use the same genesis.

Why are you generating new genesis files when you seem to have already done this with `--chain=$(pwd)/res/kapex/kapex-parachain-raw.json`?

**Comment by chrisdcosta** [comment]
Hi @shawntabrizi  these are genesis files which were used to extract the genesis state:

https://github.com/totem-tech/totem-parachains/tree/main/res/kapex

WASM blob used in file:
https://github.com/totem-tech/totem-parachains/blob/main/res/parachain-genesis-wasm.wasm

which corresponds with the files uploaded to Polkadot. The genesis state in "State 1 Output" generated today from a fresh  compile on a different OS matches these files exactly. 

The chain_spec.json file is also used in the adaptation of the chain_spec.rs file 
https://github.com/totem-tech/totem-parachains/blob/b609742c0f394a55712a0a883286b38232600b67/node/src/chain_spec.rs#L78

being called from command.rs
https://github.com/totem-tech/totem-parachains/blob/b609742c0f394a55712a0a883286b38232600b67/node/src/command.rs#L37

I was not trying to generate new one, but I would have thought that the genesis state is essentially a fingerprint, and would not give different results when the same source file was used. This is what is surprising.

**Comment by chrisdcosta** [comment]
What we actually execute on the K8s cluster uses the docker image and so is  :

```
containers:
      - command:
        - "totem-parachain-collator"
        args:
        - "--name"
        - "k-collator-1"
        - "--chain"
        - "kapex"
        - "--execution"
        - "wasm"
        - "--state-cache-size"
        - "1"
        - "--collator"
        - "--node-key-file"
        - "/data/keystore/node-key/nodekey-kapex-auth1"
        - "--node-key-type"
        - "ed25519"
        - "--keystore-path"
        - "/data/keystore/auth-key"
        - "--port"
        - "30333"
        - "--public-addr"
        - "/dns4/k-collator-1.kapex.network/tcp/44333"
        - "--prometheus-external"
        - "--"
        - "--chain"
        - "polkadot"
        - "--execution"
        - "wasm"
        - "--port"
        - "40333"
        - "--public-addr"
        - "/dns4/k-collator-1.kapex.network/tcp/44433"
        - "--prometheus-external"
```

**Comment by chrisdcosta** [comment]
Lastly these are the documented steps we did to perform the extraction of state. Probably worth a look.

https://github.com/totem-tech/totem-parachains/blob/main/scripts/extraction.sh

**Comment by bkchr** [comment]
Apply the following fix and then the printed `genesis_state` is also correct when running the node: 

```
diff --git a/node/src/command.rs b/node/src/command.rs
index 6eca28d..255cb2a 100644
--- a/node/src/command.rs
+++ b/node/src/command.rs
@@ -288,7 +288,7 @@ pub fn run() -> Result<()> {
                                        AccountIdConversion::<polkadot_primitives::v0::AccountId>::into_account(&id);
 
                                let state_version =
-                                       RelayChainCli::native_runtime_version(&config.chain_spec).state_version();
+                                       Cli::native_runtime_version(&config.chain_spec).state_version();
                                let block: Block = generate_genesis_block(&config.chain_spec, state_version)
                                        .map_err(|e| format!("{:?}", e))?;
                                let genesis_state = format!("0x{:?}", HexDisplay::from(&block.header().encode()));
@@ -447,4 +447,4 @@ impl CliConfiguration<Self> for RelayChainCli {
        fn node_name(&self) -> Result<String> {
                self.base.base.node_name()
        }
-}
\ No newline at end of file
+}
```



> 2022-06-25 09:27:12 [Parachain] Could not find the header of the genesis block in the database! block_hash=0x7838c3c774e887c0a53bcba9e64f702361a1a852d5550b86b58cd73827fa1e1e

Regarding this. My locally compiled node is reporting exactly this block hash as genesis. 

Your docker image was updated the last time in march: https://hub.docker.com/r/totemlive/totem-parachain-collator/tags While you created the chain spec for your parachain in April: https://github.com/totem-tech/totem-parachains/commit/b609742c0f394a55712a0a883286b38232600b67

For sure this will lead to an incorrect genesis block hash... Make sure to use the correct raw chain spec and it should work. You can just check the genesis block hash of your local compiled node to match the one above printed in the log output.
