### ISSUE TITLE
Enabling Offchain workers in substrate parachain template

### ISSUE THREAD

**Issue by rafat** [substrate-developer-hub/substrate-parachain-template#134]
I know the way to enable Offchain workers in a solo chain is to edit the service.rs as per the documentation and it works perfectly. I have tried to make equivalent changes to the service.rs in my parachain but offchain_workers function is never triggered. Can anyone tell me if there is a way to make it happen for a parachain because I can't quite figure out all the configuration changes that need to be done in this case ? I am running the parachain with the --offchain-worker=always flag as well but the offchain worker hook is never called.

**Comment by brunopgalvao** [comment]
Please consider re-opening this upstream:
- https://github.com/paritytech/cumulus/issues

**Comment by rafat** [comment]
I have opened the issue here https://github.com/paritytech/cumulus/issues/1849 .=
