### ISSUE TITLE
Error parsing spec file: control character

### ISSUE THREAD

**Issue by mrcnski** [substrate-developer-hub/substrate-parachain-template#140]
I'm following [this tutorial](https://docs.substrate.io/tutorials/connect-relay-and-parachains/connect-a-local-parachain/) and I get an error creating the chainspec.

I do this:

```
./target/release/parachain-template-node build-spec --disable-default-bootnode > plain-parachain-chainspec.json
```

update the para ID values, then run:

```
./target/release/parachain-template-node build-spec --chain plain-parachain-chainspec.json --disable-default-bootnode --raw > raw-parachain-chainspec.json
```

Inspecting the output file, I see this:

```
Error: Input("Error parsing spec file: control character (\\u0000-\\u001F) found while parsing a string at line 19 column 130688")
```

**Comment by NukeManDan** [comment]
Just tried this as you stated, verbatum, no error. :shrug: 
Please update to the 0.9.37 tag and try again
