### ISSUE TITLE
Fix CI/CD job for updating template

### ISSUE THREAD

**Issue by sacha-l** [substrate-developer-hub/substrate-parachain-template#143]
Pending https://github.com/paritytech/release-engineering/issues/142

**Comment by coderobe** [comment]
diener also needs to be updated in the ci env

**Comment by sacha-l** [comment]
Who can we ping to help with updating Diener ?

**Comment by NukeManDan** [comment]
Hope #149 is the last time this needs to be fixed :pray:  and a code owner file needs to be made cc @lisa-parity @sacha-l  ala https://github.com/substrate-developer-hub/substrate-node-template/pull/406

**Comment by joao-paulo-parity** [comment]
The job should work correctly after

- https://github.com/paritytech/polkadot/pull/6679 is merged
- https://github.com/paritytech/scripts/pull/506 is merged and `ci-linux` is rebuilt, which should take care of https://github.com/paritytech/pipeline-scripts/issues/97

**Comment by joao-paulo-parity** [comment]
Follow-up to https://github.com/substrate-developer-hub/substrate-parachain-template/issues/143#issuecomment-1420736469:

- https://github.com/paritytech/polkadot/pull/6679 was merged
- The diener version was updated for `update_substrate_template` in https://github.com/paritytech/pipeline-scripts/pull/98

Therefore the templates automation should be working from now on.

I've submitted the update PR for `substrate-node-template` yesterday: https://github.com/substrate-developer-hub/substrate-node-template/pull/413

**Comment by sacha-l** [comment]
Seems to work as expected now. Thank you @joao-paulo-parity ! 🙏
