### ISSUE TITLE
Upgrade 0.9.37

### ISSUE THREAD

**Issue by Chralt98** [substrate-developer-hub/substrate-parachain-template#150]
XCMv3 is part of this polkadot upgrade. When could we expect a merge into the main branch?

What are the negative consequences to use the `autoupdate_polkadot-v0.9.37_2023-01-17_16-16-15` branch? Why do we get four different `v0.9.37` branches?

**Comment by NukeManDan** [comment]
The CI is triggered upstream when draft releases are made `rc-x` for Polkadot. The most recent is always the one to use. 
#149 is now in place.
