### ISSUE TITLE
why do not open rpc function in this template

### ISSUE THREAD

**Issue by transxask** [substrate-developer-hub/substrate-parachain-template#16]
hello guys! I used this template to create my parachain,  but when i connected my node by rpc, it  did not works.

could you add the rpc.rs to this template in the next commit? thanks.

**Comment by NukeManDan** [comment]
Hey, sorry you ran into trouble!
Can you provide a https://stackoverflow.com/help/minimal-reproducible-example to help us help you? 
And specifically a request for what to include?

**Comment by transxask** [comment]
Thanks, i solved it.
