### ISSUE TITLE
dependencies updated to be more clear

### ISSUE THREAD

**Issue by GopherJ** [substrate-developer-hub/substrate-parachain-template#17]
https://github.com/substrate-developer-hub/substrate-parachain-template/blob/master/node/Cargo.toml#L11-L198

Although it looks great that we can list dependencies like this, but I'm still wondering what's the advantage?

It makes things not clear at all. No body can know what's the dependencies used at the first glance.

It's a good feature but not pratical at all. Hope you can consider about this.

**Comment by NukeManDan** [comment]
Not clear compared to what? 
This is used to specify a git instead of cargo as the place to pull the crates from, with a specific branch/tag/release to use as needed.

**Comment by GopherJ** [comment]
@NukeManDan why cannot we write in one line?

**Comment by GopherJ** [comment]
> This is used to specify a git instead of cargo as the place to pull the crates from, with a specific branch/tag/release to use as needed.

we can still write it in one line...

**Comment by NukeManDan** [comment]
Sure, its a style decision. As the more items you add the more complex it becomes. I don't think one is the "right" way. If you find it easier to read as single lines, by all means write it this way. I hope you understand it's not big enough of an issue to force one way or the other.

When the features are stable on crates we will likely use the single line style.

**Comment by GopherJ** [comment]
@NukeManDan If you agree with me I can find time to make a PR for this, currently it's really hard for me to understand what dependencies have been used in this project.

especially `dependencies.xxx` will make other parts in `Cargo.toml` not that clear.

**Comment by riusricardo** [comment]
I agree that one line dependencies could look nice but as Dan said it isn't an issue. Both ways work so it isn't a priority to change it.

**Comment by riusricardo** [comment]
>Although it looks great that we can list dependencies like this, but I'm still wondering what's the advantage?

There is no advantage it is related to a script that we use to generate the substrate-node-template. It makes the update process smoother.

**Comment by NukeManDan** [comment]
@GopherJ if you are willing to put in a PR, I think we are open to include it 😁

**Comment by NukeManDan** [comment]
@GopherJ  are you still interested in doing this? 😁 
let us know 🙏🏼

**Comment by GopherJ** [comment]
@NukeManDan yes sorry I was busy these weeks, hope I can do this during the next holiday

**Comment by GopherJ** [comment]
I'll open a PR when I get more time...close it for now~
