### ISSUE TITLE
no matching package named `cumulus-pallet-xcm-handler` found

### ISSUE THREAD

**Issue by ksr30** [substrate-developer-hub/substrate-parachain-template#19]
no matching package named `cumulus-pallet-xcm-handler` found
```
    Updating crates.io index
    Updating git repository `https://github.com/paritytech/cumulus.git`
    Updating git repository `https://github.com/paritytech/substrate.git`
    Updating git repository `https://github.com/paritytech/polkadot`
error: no matching package named `cumulus-pallet-xcm-handler` found
location searched: https://github.com/paritytech/cumulus.git?branch=rococo-v1
```

**Comment by riusricardo** [comment]
Are you updating the commits to follow the latest rococo-v1? If that is the case you should take a looks to the changes that happen inside this directory. https://github.com/paritytech/cumulus/tree/rococo-v1/rococo-parachains
You will see that there is an xcm revamp going on.
