### ISSUE TITLE
Is there any branch or source which is fit for v2.0.1

### ISSUE THREAD

**Issue by tinydjp** [substrate-developer-hub/substrate-parachain-template#20]
We just built our private chain using substrate 2.0.1 a few days before v 3.0 release. Is there any alternative to keep using 2.0.1  to build a parachain instead of 3.0.

**Comment by jimmychu0807** [comment]
Hi @tinydjp, nice meeting you here 😄 
The thing is parachain is still a continuously evolving component (together with the relay-chain counterpart [polkadot `rococo-v1` branch](https://github.com/paritytech/polkadot/tree/rococo-v1)). So I would suspect there is no backward compatibility yet at this point. 

It maybe better for you to upgrade your node logic and runtime to v3. This need to be done sooner or later anyway, and then experiment with the parachain side. Be warned this is continuously evolving (but should be stabilised soon).

**Comment by NukeManDan** [comment]
If you need help, let us know in [subport](https://github.com/paritytech/subport/issues) to get you to v3 😁
