### ISSUE TITLE
Work on a PoE tutorial in the parachain context

### ISSUE THREAD

**Issue by jimmychu0807** [substrate-developer-hub/substrate-parachain-template#22]
Related to: https://github.com/substrate-developer-hub/substrate-node-template/issues/71

I agree with the OP that it is great having a side tutorial building PoE runtime in parachain context that connect to relay chain.

I will help contribute to this, say maybe in 1-2 weeks.

**Comment by riusricardo** [comment]
@jimmychu0807  That is a good idea but it won't take 2 weeks. This task will take more than 4 weeks. You will need to understand the ins and outs of Cumulus.
Integrating a new consensus into Cumulus isn't straight forward.

**Comment by NukeManDan** [comment]
Ah I think this means the PoE pallet example - just storing a hash of a file on chain as PoE. So not that big of a push to get this already existing tutorail updated...
https://substrate.dev/docs/en/tutorials/build-a-dapp/

Maybe as a new section? Or an "alternative" one?

**Comment by NukeManDan** [comment]
closing in favor of putting this example in the cumulus workshop https://github.com/substrate-developer-hub/cumulus-workshop/issues/56
