### ISSUE TITLE
error[E0152]: found duplicate lang item `panic_impl`

### ISSUE THREAD

**Issue by GopherJ** [substrate-developer-hub/substrate-parachain-template#23]
# reproduce steps:

1. git clone https://github.com/substrate-developer-hub/substrate-parachain-template
2. cd substrate-parachain-template/runtime
3. cargo check --target wasm32-unknown-unknown --no-default-features

![image](https://user-images.githubusercontent.com/33961674/115146507-63303700-a089-11eb-9ded-85a5b68c06f2.png)

**Comment by NukeManDan** [comment]
I am not sure why you are using the wasm target here... can you explain what you are trying to do? `cargo build --release` on the latest `master` here works without issue for me.

**Comment by GopherJ** [comment]
@NukeManDan from what I understood, runtime should be able to be compiled into `wasm`, but it's not the case here.

I tried to do the same thing on `Acala/Mandala` runtime, it compiles fine while running:

```
cargo check --target wasm32-unknown-unknown --no-default-features
```

**Comment by NukeManDan** [comment]
@GopherJ Please do let us know if you still have issues, I hope that #33 will resolve this anyhow.
