### ISSUE TITLE
Add a strong notice if the template is rococo compatible

### ISSUE THREAD

**Issue by NukeManDan** [substrate-developer-hub/substrate-parachain-template#25]
A flag in the README that let's you know STRONGLY if it's rococo compatible or not. 
We (Parity support team) must maintain this warning, trigger a warning on rococo resets until it's updated and go to "all good" status for comparability.

**Comment by al3mart** [comment]
This [commit](765c00daf0fc032e10f401a053c31d3ee6423f5d) closes the issue
