### ISSUE TITLE
Build is failing while following cumulus-workshop

### ISSUE THREAD

**Issue by ayushmishra2005** [substrate-developer-hub/substrate-parachain-template#37]
I am trying to follow https://substrate.dev/cumulus-workshop/#/en/1-prep/1-compiling?id=building-the-collator-template

I am using 1e1e725 commit of https://github.com/substrate-developer-hub/substrate-parachain-template

but build is failing

![error](https://user-images.githubusercontent.com/1575561/119675479-b3ee3900-be5a-11eb-8701-d22e46bb6738.png)

**Comment by ayushmishra2005** [comment]
I tried to use latest branch. but still getting

```

  --- stderr


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-arch" "arm64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-DSNAPPY=1" "-DNDEBUG=1" "-DOS_MACOSX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/Users/ayushkumarmishra/workspace/substrate-parachain-template/target/release/build/librocksdb-sys-8485750f41910073/out/rocksdb/util/crc32c.o" "-c" "rocksdb/util/crc32c.cc" with args "c++" did not execute successfully (status code exit code: 1).


```

**Comment by NukeManDan** [comment]
this is a M1 ARM machine? Likely you must mitigate: https://github.com/substrate-developer-hub/substrate-node-template/issues/179
