### ISSUE TITLE
pallet-contracts cannot work in substrate-parachain-template

### ISSUE THREAD

**Issue by szout** [substrate-developer-hub/substrate-parachain-template#43]
I use substrate-developer-hub/substrate-parachain-template (from rococo-v1 update to polkadotv0.9.3), the parachain block import is ok,but after add  pallet-contracts the parachain block height is stop.

**Comment by szout** [comment]
use this repo https://github.com/szout/substrate-parachain-template.git, only add pallee-contracts , when parachain runing, press UI <update & deploy code> button,  pls use /scripts/flipper.contract.

**Comment by NukeManDan** [comment]
Please link me to a forked repo where you have this code to test against at least

**Comment by NukeManDan** [comment]
> Sandbox is currently not provided 

From the team: cumulus does not yet support the contracts pallet yet. 
There is no tracking issue for this as of yet. Please join us on https://matrix.to/#/#parachain-technical:matrix.parity.io to follow updates
