### ISSUE TITLE
Thread 'main' panicked at 'Missing para_id' (when attempting to build-spec for parachain-collator)

### ISSUE THREAD

**Issue by sgoodenough95** [substrate-developer-hub/substrate-parachain-template#54]
Hi, when following along to the README the compiler panics when attempting to build the chain-spec for the collator node. Please find my console log below.

`samuelgoodenough@Samuels-MBP substrate-parachain-template % ./target/release/parachain-collator build-spec --disable-default-bootnode > ./resources/template-local-plain.json

====================

Version: 3.0.0-cdc5e5e-x86_64-macos

   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:595:17
   4: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:497:13
   5: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/sys_common/backtrace.rs:141:18
   6: rust_begin_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:493:5
   7: core::panicking::panic_fmt
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/panicking.rs:92:14
   8: core::option::expect_failed
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/option.rs:1241:5
   9: sc_cli::config::CliConfiguration::create_configuration
  10: sc_cli::runner::Runner<C>::new
  11: parachain_collator::main
  12: std::sys_common::backtrace::__rust_begin_short_backtrace
  13: std::rt::lang_start::{{closure}}
  14: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:379:40
      std::panicking::try
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panicking.rs:343:19
      std::panic::catch_unwind
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/panic.rs:431:14
      std::rt::lang_start_internal
             at /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/std/src/rt.rs:34:21
  15: _main

Thread 'main' panicked at 'Missing para_id', node/src/command.rs:68

This is a bug. Please report it at:

        https://github.com/substrate-developer-hub/substrate-parachain-template/issues/new`

Cheers, Sam

**Comment by NukeManDan** [comment]
`para_id` is required now, @al3mart can you update the readme with instructions needed? 🙏🏼

**Comment by al3mart** [comment]
that's it, this [PR](https://github.com/substrate-developer-hub/substrate-parachain-template/pull/48) went through lacking some documentation alongside 

@sgoodenough95 for the moment, you can undo the changes that PR introduces so you can keep working.

Meanwhile we will add some instructions

**Comment by sgoodenough95** [comment]
thank you @al3mart ! Yes I am using the previous commit for now which is compiling fine :)
