### ISSUE TITLE
Add sensible default XCM config

### ISSUE THREAD

**Issue by apopiak** [substrate-developer-hub/substrate-parachain-template#62]
The current XCM config in the template is mostly copied from the parachains in the cumulus repo (AFAICT):
https://github.com/substrate-developer-hub/substrate-parachain-template/blob/9b41b90fa241ea36563bf1f5cefca0bdd2543c26/runtime/src/lib.rs#L383-L396

We probably want to default to a config that is more suitable for a community parachain (e.g. disallow teleports) and point out which things to adjust.

**Comment by NukeManDan** [comment]
I can change this. I very much also would like to add and explanation and how-to use in the https://github.com/substrate-developer-hub/cumulus-workshop/ about _how_ to use it. Is that something you could support me on @apopiak? 

Also we get this template from upstream on a Polkadot & Cumulus releases. I will wait for v0.9.9 to land before this is incorporated, if that is OK.

**Comment by apopiak** [comment]
Sounds good!

**Comment by NukeManDan** [comment]
Simply disabled teleports in #65 - if you want to change more than that, let's discuss further (we can reopen this issue)
