### ISSUE TITLE
`Failed to get runtime version: RuntimeConstruction(Other("cannot deserialize module: InvalidMagic"))`

### ISSUE THREAD

**Issue by garrettmaring** [substrate-developer-hub/substrate-parachain-template#63]
When starting a collator with Alice (https://substrate.dev/cumulus-workshop/#/en/3-parachains/1-launch?id=start-the-collator-node), I receive an error when attempting to load GRANDPA authority.

![Screen Shot 2021-08-12 at 8 15 04 AM](https://user-images.githubusercontent.com/8270120/129222270-5b2f3858-c127-48fc-a802-bf535e72d87c.png)

**Comment by NukeManDan** [comment]
Looks like you are using the correct template commit to build, are you positive you have a proper chain-spec? You can try to build one yourself as per the workshop if you have not already. And also no prexisting DB (purge command or removing the entire base path dir should do).

**Comment by garrettmaring** [comment]
I downloaded the custom-raw-2 file listed in one of the previous workshop steps from https://substrate.dev/cumulus-workshop/shared/chainspecs/rococo-custom-2-raw.json

Should I instead download the plain spec and generate the raw locally?

For further context, using that downloaded raw spec works for starting a single validator but running a second validator produces the same error as running this collator (InvalidMagic).

**Comment by NukeManDan** [comment]
A second `bob` validator for your relay chain? Or do you mean _collator_ for your parachain? You can only have one node running with the same keys per network btw. 
https://substrate.dev/cumulus-workshop/#/en/3-parachains/4-more-nodes

Error stems from a decode issue, so I suspect 
 https://github.com/paritytech/substrate/blob/631d4cdbcad438248c2597213918d8207d85bf6e/client/executor/common/src/error.rs#L98
https://github.com/paritytech/parity-wasm/blob/329d037cea8fa621e957e95e880537ff28e54c8f/src/elements/module.rs#L585

**Comment by garrettmaring** [comment]
"You can only have one node running with the same keys per network btw." this makes sense! The issue does seem to have been some bad local state in `/tmp`. Clearing that out removed the error and the collator is running correctly 🥂
