### ISSUE TITLE
Using `pallet-contracts` with parachain template

### ISSUE THREAD

**Issue by garrettmaring** [substrate-developer-hub/substrate-parachain-template#64]
I am upgrading my project from the [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template) to the [substrate-parachain-template](https://github.com/substrate-developer-hub/substrate-parachain-template).

I removed by changes for off-chain extensions and am starting with porting just [pallet-contracts](https://substrate.dev/docs/en/tutorials/add-contracts-pallet/#exposing-the-contracts-api) to support [`ink!`](https://substrate.dev/substrate-contracts-workshop/#/0/building-your-contract).

The [contracts pallet tutorial](https://substrate.dev/docs/en/tutorials/add-contracts-pallet/#exposing-the-contracts-api) has been upgraded to support `v4.0.0` but the parachain template is still using `v3.0.0` dependencies. To resolve an issue resolving `parity-util-mem` when copying the tutorial code as is, I only needed to update the runtime config code to support v3.0.0. I was able to get the project compiling but without any of the RPC steps from the tutorial.

I've now started one collator (Alice) and used the local node identity printed there to start one validator (Bob).

![Screen Shot 2021-08-16 at 8 26 55 AM](https://user-images.githubusercontent.com/8270120/129588809-c7d2aa6e-4646-447b-876a-f7eed82c80fa.png)

Which of the WebSocket ports should I connect to upload & instantiate contracts?

I eventually found a port (8844) where the 'Contracts' tab would show. However, uploading & instantiating a compiled ink contracts hangs on the 'ready' message.

![Screen Shot 2021-08-16 at 8 32 30 AM](https://user-images.githubusercontent.com/8270120/129589553-54a90a09-18f1-4730-86cf-f841c386bbdf.png)

I have the web console debugger open yet don't see any error messages there.

Do I need to add the RPC segments from the tutorial to the parachain template service somehow? Am I starting the validator + collator correctly (who's bootnode, etc.)? Any way to see more logging underthehood?

Cheers

**Comment by NukeManDan** [comment]
Unfortunately at this time the sandboxing for the para-runtime in the relaychain needed to run the contracts pallet is not available for cumulus, and thus parachains cannot use the contracts pallet. I do not have an issue to point to tracking the progress on this upstream for you unfortunately either.

Please join https://matrix.to/#/#parachain-technical:matrix.parity.io and ask in there for an update (and anyone looking at this issue latter). It is a highly sought feature though, so I would expect some progress here soon.

**Comment by NukeManDan** [comment]
Ah there is a tracking issue: 
https://github.com/paritytech/substrate/issues/9354

Once this is completed, expect there to be some further testing and shortly after the ability to use the contracts pallet 🤞🏼
