### ISSUE TITLE
`main` not building

### ISSUE THREAD

**Issue by apopiak** [substrate-developer-hub/substrate-parachain-template#92]
`main` currently depends on Polkadot 0.9.15-1 and Cumulus 0.9.15 which in turn depend on different versions of Substrate so the build fails.

**Comment by NukeManDan** [comment]
Damn. This was confirmed to build locally for me, I do not see a 15-1 upstream on cumulus. what should be used @apopiak ?

**Comment by NukeManDan** [comment]
Closing as #93 removes the need for 0.9.15-1, I think. If you disagree, let's re-open this issue :pray: 
I for sure make `main` build here.
