### ISSUE TITLE
Build error when trying to do poe example

### ISSUE THREAD

**Issue by StringNick** [substrate-developer-hub/substrate-parachain-template#97]
Hello, when i trying to import library sp_std for Vec as in an example on substrate.dev, on this template on build error:
```
error[E0277]: the trait bound `Vec<u8>: MaxEncodedLen` is not satisfied
  #[pallet::pallet]
   |               ^^^^^^ the trait `MaxEncodedLen` is not implemented for `Vec<u8>`

```
I import sp_std with branch = "polkadot-v0.9.16", and as in an example 4.0.0-dev, same errors.
I am using vectors in events, storage and function
`	pub(super) type Applications<T: Config> = StorageMap<_, Blake2_128Concat, T::AccountId, **Vec<u8>**, ValueQuery>;
`

**Comment by NukeManDan** [comment]
This should be resolved in 0.9.17 update #101 - please wait for that to land and give it another shot? Or try the code from the branch and LMK if the node builds :)

**Comment by StringNick** [comment]
I tried last version of template parachain, changed storagevalue from u32 to vec<u8>, sp_std is imported too.
Same error, as in now standart node-template(before polkadot v0.9.17 it was working with sp_std, vector in storage)
Issue in sub example without para https://github.com/substrate-developer-hub/substrate-node-template/issues/315

**Comment by popov-vladimir** [comment]
I've caught the same exception with kitties tutorial after some sp_ packages have updated to 5.0

```
28 | pub trait MaxEncodedLen: Encode {
   |           ^^^^^^^^^^^^^

error[E0277]: the trait bound `Kitty<T>: parity_scale_codec::MaxEncodedLen` is not satisfied
  --> pallets/kitties/src/lib.rs:31:12
   |
31 |     #[pallet::pallet]
   |               ^^^^^^ the trait `parity_scale_codec::MaxEncodedLen` is not implemented for `Kitty<T>`
   |
   = note: required because of the requirements on the impl of `StorageInfoTrait` for `frame_support::pallet_prelude::StorageMap<_GeneratedPrefixForStorageKitties<T>, frame_support::Twox64Concat, <T as frame_system::Config>::Hash, Kitty<T>>`
```

Is there a way to downgrade to 4.0.0-dev?

I tried to explore the issue in the code of the substrate package, but I just can't find why StorageInfoTrait is needed for StorageMap, and how to fix it ( afaik it's impossible to just impl a foreign trait in my project)

And an off-top question: is there a way to prevent such a breaking upgrade in a local project?  I have pulled my repo from a new laptop with everything including Cargo.lock . For somewhat similar tools ( e. g. pip, npm  etc) the purpose of the lockfile is exactly to make builds reproducible. But with cargo and substrate I've experienced the opposite experience : although the repo was identical, new version have been pulled and broke the the project.

**Comment by flipchan** [comment]
same problem here:
https://github.com/flipchan/frontier-pallet-upstream

**Comment by ceruleanstreak** [comment]
> 31 |     #[pallet::pallet]
>    |               ^^^^^^ the trait `parity_scale_codec::MaxEncodedLen` is not implemented for `Kitty<T>`
>    |

Temporary solution here is to use` #[pallet::without_storage_info]` on top of `pub struct Pallet<T>(_);`

**Comment by popov-vladimir** [comment]
> > 31 |     #[pallet::pallet]
> > |               ^^^^^^ the trait `parity_scale_codec::MaxEncodedLen` is not implemented for `Kitty<T>`
> > |
> 
> Temporary solution here is to use` #[pallet::without_storage_info]` on top of `pub struct Pallet<T>(_);`

This actually works, seen it here also:
https://substrate.stackexchange.com/questions/544/maxencodedlen-is-not-implemented-for-vecu8

I still don’t quite get it whether  this is a legit solution or a dirty hack. 
what if I actually want to specify maximum size, how could it be done?

**Comment by StringNick** [comment]
> > > 31 |     #[pallet::pallet]
> > > |               ^^^^^^ the trait `parity_scale_codec::MaxEncodedLen` is not implemented for `Kitty<T>`
> > > |
> > 
> > 
> > Temporary solution here is to use` #[pallet::without_storage_info]` on top of `pub struct Pallet<T>(_);`
> 
> This actually works, seen it here also: https://substrate.stackexchange.com/questions/544/maxencodedlen-is-not-implemented-for-vecu8
> 
> I still don’t quite get it whether this is a legit solution or a dirty hack. what if I actually want to specify maximum size, how could it be done?

I cant find a solution for BoundedVec, temporary i am using [u8; 64] - this format, can someone help, how can i use this format in boundedvec, u8 array with 64 fixed-size

**Comment by NukeManDan** [comment]
solved with https://github.com/substrate-developer-hub/substrate-docs/pull/861
