### ISSUE TITLE
v0.9.16 runtime-benchmarks failed

### ISSUE THREAD

**Issue by decentration** [substrate-developer-hub/substrate-parachain-template#98]
Fresh [parachain-template ](https://github.com/substrate-developer-hub/substrate-parachain-template)

i ran `cargo build --features runtime-benchmarks`

```cli
error[E0046]: not all trait items implemented, missing: `successful_origin`
    --> /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/4aeb95f/frame/society/src/lib.rs:1268:1
     |
1268 | impl<T: Config> EnsureOrigin<T::Origin> for EnsureFounder<T> {
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `successful_origin` in implementation
     |
     = help: implement the missing item: `fn successful_origin() -> OuterOrigin { todo!() }`
 ```

But it looks like `fn successful_origin()` is already [there](https://github.com/paritytech/substrate/blob/4aeb95f7f38fcd519e2628f32f79044a8fef99d5/frame/society/src/lib.rs#L1278):

```rust
/// Simple ensure origin struct to filter for the founder account.
pub struct EnsureFounder<T>(sp_std::marker::PhantomData<T>);
impl<T: Config> EnsureOrigin<T::Origin> for EnsureFounder<T> {
	type Success = T::AccountId;
	fn try_origin(o: T::Origin) -> Result<Self::Success, T::Origin> {
		o.into().and_then(|o| match (o, Founder::<T>::get()) {
			(frame_system::RawOrigin::Signed(ref who), Some(ref f)) if who == f => Ok(who.clone()),
			(r, _) => Err(T::Origin::from(r)),
		})
	}

	#[cfg(feature = "runtime-benchmarks")]
	fn successful_origin() -> T::Origin {
		let founder = Founder::<T>::get().expect("society founder should exist");
		T::Origin::from(frame_system::RawOrigin::Signed(founder))
	}
}
```

**Comment by decentration** [comment]
my mistake it seems `cargo build --release --features runtime-benchmarks` causes an error but `cargo build --features runtime-benchmarks` completes the job.

**Comment by decentration** [comment]
actually no, even with `cargo build --features runtime-benchmarks still same above error.

**Comment by decentration** [comment]
Also the society pallet isnt being used in parachain template

**Comment by decentration** [comment]
@NukeManDan can you help on this issue? : )

**Comment by NukeManDan** [comment]
looks to be fixed by https://github.com/substrate-developer-hub/substrate-parachain-template/commit/4bdc77a13a36fa261010aca4a6ae147d8bee6630 ?

**Comment by NukeManDan** [comment]
Confirmed to run with that command in https://github.com/substrate-developer-hub/substrate-node-template/issues/267
