### ISSUE TITLE
Adapt pallet_xcm's defaults for Teleports & Reserve transfers

### ISSUE THREAD

**Issue by stiiifff** [substrate-developer-hub/substrate-parachain-template#99]
The current defaults for pallet_xcm's Config are counter-intuitive as they imply any asset teleport is allowed (though is already disabled in XcmConfig) and Reserve transfers are not:
```rust
impl pallet_xcm::Config for Runtime {
	// ...
	type XcmTeleportFilter = Everything;
	type XcmReserveTransferFilter = Nothing;
}
```

Inverting the values to not allow any Teleport and allowing Reserver transfers would be better defaults:

```rust
impl pallet_xcm::Config for Runtime {
	// ...
	type XcmTeleportFilter = Nothing;
	type XcmReserveTransferFilter = Everything;
}
```

**Comment by NukeManDan** [comment]
@stiiifff this should be included upstream, no? We can propagate here.

**Comment by stiiifff** [comment]
@NukeManDan yep !

**Comment by NukeManDan** [comment]
https://github.com/paritytech/cumulus/pull/1901
